"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { apiFetch } from "@/lib/api";

type ScanLocation = "ESTADIO" | "HOTEL" | "GIMNASIO" | "CASINO";

type Provider = { id: string; name?: string | null; type?: string | null };
type ProviderParticipant = {
  id: string;
  fullName: string;
  providerId: string;
  metadata?: Record<string, any> | null;
  status?: string | null;
};

type StaffProfile = {
  id: string;
  fullName: string;
  providerId: string;
  providerName: string;
};

type DecodedCredential = {
  fullName: string;
  delegation: string;
  discipline: string;
  eventName: string;
  subjectType: string;
  code: string;
  rawValue: string;
};

type ScanRecord = DecodedCredential & {
  location: ScanLocation;
  scannedAt: string;
  authorized: boolean;
  reason: string;
};

const STORAGE_KEY = "portal_access_control_staff";

const SCAN_LOCATIONS: Array<{
  value: ScanLocation;
  label: string;
  color: string;
  bg: string;
  border: string;
}> = [
  { value: "ESTADIO", label: "Estadio", color: "#3b82f6", bg: "rgba(59,130,246,0.08)", border: "rgba(59,130,246,0.3)" },
  { value: "HOTEL", label: "Hotel", color: "#10b981", bg: "rgba(16,185,129,0.08)", border: "rgba(16,185,129,0.3)" },
  { value: "GIMNASIO", label: "Gimnasio", color: "#f59e0b", bg: "rgba(245,158,11,0.08)", border: "rgba(245,158,11,0.3)" },
  { value: "CASINO", label: "Casino", color: "#a855f7", bg: "rgba(168,85,247,0.08)", border: "rgba(168,85,247,0.3)" },
];

const LOCATION_ICONS: Record<ScanLocation, JSX.Element> = {
  ESTADIO: (
    <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
      <ellipse cx="12" cy="5" rx="9" ry="3" /><path d="M21 5v14a9 3 0 0 1-18 0V5" /><path d="M3 12a9 3 0 0 0 18 0" />
    </svg>
  ),
  HOTEL: (
    <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
      <path d="M3 22V8l9-6 9 6v14" /><path d="M9 22V12h6v10" /><rect x="9" y="7" width="2" height="2" /><rect x="13" y="7" width="2" height="2" />
    </svg>
  ),
  GIMNASIO: (
    <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
      <path d="M6 4v16" /><path d="M18 4v16" /><path d="M6 12h12" /><path d="M2 9h4" /><path d="M2 15h4" /><path d="M18 9h4" /><path d="M18 15h4" />
    </svg>
  ),
  CASINO: (
    <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
      <rect x="2" y="3" width="20" height="14" rx="2" /><path d="M8 21h8" /><path d="M12 17v4" />
    </svg>
  ),
};

// Parse either URL-style QR or multi-line text QR (the actual format generated by the platform)
function parseCredentialQr(rawValue: string): DecodedCredential {
  // Try URL format first
  try {
    const url = new URL(rawValue);
    const fullName = url.searchParams.get("name") || "Sin nombre";
    const delegation = url.searchParams.get("delegation") || "Sin delegación";
    const discipline = url.searchParams.get("discipline") || "Sin disciplina";
    const eventName = url.searchParams.get("event") || "Evento";
    const subjectType = url.searchParams.get("subjectType") || "PARTICIPANT";
    const code = url.searchParams.get("id") || url.searchParams.get("code") || "";
    return { fullName, delegation, discipline, eventName, subjectType, code, rawValue };
  } catch {
    // Fall through to multi-line parser
  }

  // Multi-line text format: "Participante: X\nID: abc123\nDelegación: CHL" etc
  const lines = rawValue.split("\n").map((l) => l.trim());
  let fullName = "Sin nombre";
  let delegation = "Sin delegación";
  let discipline = "Sin disciplina";
  let eventName = "Evento";
  let subjectType = "PARTICIPANT";
  let code = "";

  lines.forEach((line) => {
    const [key, ...rest] = line.split(":");
    const value = rest.join(":").trim();
    if (!value) return;
    const k = key.trim().toLowerCase();
    if (k === "participante" || k === "nombre") {
      fullName = value;
    } else if (k === "conductor") {
      fullName = value;
      subjectType = "DRIVER";
    } else if (k === "id" || k === "código" || k === "codigo") {
      code = value;
    } else if (k === "delegación" || k === "delegacion") {
      delegation = value;
    } else if (k === "disciplina") {
      discipline = value;
    } else if (k === "evento") {
      eventName = value;
    } else if (k === "rut") {
      // RUT present → likely a driver credential
      if (subjectType === "PARTICIPANT") subjectType = "DRIVER";
    }
  });

  if (!code) {
    // Fallback: last 6 alphanumeric of the raw string
    const alphanum = rawValue.replace(/[^A-Za-z0-9]/g, "");
    if (alphanum.length >= 4) code = alphanum.slice(-6);
  }

  if (!code) {
    throw new Error("El QR no contiene un código de credencial reconocible.");
  }

  return { fullName, delegation, discipline, eventName, subjectType, code, rawValue };
}

function formatScanTimestamp(date: Date) {
  return date.toLocaleString("es-CL", {
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
    second: "2-digit",
  });
}

export default function AccessControlPortalPage() {
  // ── Staff auth state
  const [codeInput, setCodeInput] = useState("");
  const [authError, setAuthError] = useState<string | null>(null);
  const [authLoading, setAuthLoading] = useState(false);
  const [staff, setStaff] = useState<StaffProfile | null>(null);

  // ── Request access form state
  const [requestEmail, setRequestEmail] = useState("");
  const [requestLoading, setRequestLoading] = useState(false);
  const [requestError, setRequestError] = useState<string | null>(null);
  const [requestStatus, setRequestStatus] = useState<string | null>(null);

  // ── Scanner state (mirrors ScannerPortal)
  const regionId = useMemo(() => `qr-reader-${Math.random().toString(36).slice(2, 10)}`, []);
  const scannerRef = useRef<any>(null);
  const [selectedLocation, setSelectedLocation] = useState<ScanLocation>("ESTADIO");
  const [scannerReady, setScannerReady] = useState(false);
  const [scanning, setScanning] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [currentScan, setCurrentScan] = useState<ScanRecord | null>(null);
  const [history, setHistory] = useState<ScanRecord[]>([]);
  const [flashOk, setFlashOk] = useState(false);
  const [flashDenied, setFlashDenied] = useState(false);

  // Restore persisted session on mount
  useEffect(() => {
    try {
      const raw = sessionStorage.getItem(STORAGE_KEY);
      if (raw) setStaff(JSON.parse(raw));
    } catch {}
  }, []);

  // Boot scanner when authenticated
  useEffect(() => {
    if (!staff) return;
    let active = true;
    async function boot() {
      const { Html5Qrcode } = await import("html5-qrcode");
      if (!active) return;
      scannerRef.current = new Html5Qrcode(regionId);
      setScannerReady(true);
    }
    void boot();
    return () => {
      active = false;
      const instance = scannerRef.current;
      scannerRef.current = null;
      if (instance?.isScanning) void instance.stop().catch(() => undefined);
      void instance?.clear?.()?.catch?.(() => undefined);
    };
  }, [regionId, staff]);

  // ── Auth
  const attemptAuth = async () => {
    setAuthError(null);
    setAuthLoading(true);
    try {
      const [providers, participants] = await Promise.all([
        apiFetch<Provider[]>("/providers"),
        apiFetch<ProviderParticipant[]>("/provider-participants"),
      ]);
      const staffProviderIds = new Set(
        (providers || [])
          .filter((p) => String(p.type ?? "").toLowerCase() === "staff")
          .map((p) => p.id),
      );
      const normalized = codeInput.trim().toLowerCase();
      const match = (participants || []).find((p) => {
        if (!staffProviderIds.has(p.providerId)) return false;
        if ((p.status ?? "").toUpperCase() === "DISABLED") return false;
        return p.id.slice(-6).toLowerCase() === normalized;
      });
      if (!match) {
        setAuthError(
          "Código no válido o no corresponde a un participante registrado como proveedor tipo Staff.",
        );
        return;
      }
      const providerName = (providers || []).find((p) => p.id === match.providerId)?.name || "";
      const profile: StaffProfile = {
        id: match.id,
        fullName: match.fullName,
        providerId: match.providerId,
        providerName,
      };
      setStaff(profile);
      try {
        sessionStorage.setItem(STORAGE_KEY, JSON.stringify(profile));
      } catch {}
    } catch (err) {
      setAuthError(err instanceof Error ? err.message : "Error de autenticación");
    } finally {
      setAuthLoading(false);
    }
  };

  const requestAccess = async () => {
    if (!requestEmail.trim()) return;
    setRequestLoading(true);
    setRequestError(null);
    setRequestStatus(null);
    try {
      const response = await apiFetch<{ message?: string }>(
        "/access-control/request-access",
        {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ email: requestEmail.trim() }),
        },
      );
      setRequestStatus(response?.message || "Código enviado al correo");
    } catch (err) {
      const raw = err instanceof Error ? err.message : "";
      let message = raw;
      try {
        const parsed = JSON.parse(raw);
        if (parsed?.message) message = parsed.message;
      } catch {}
      setRequestError(message || "No se pudo solicitar el código");
    } finally {
      setRequestLoading(false);
    }
  };

  const logout = async () => {
    if (scannerRef.current?.isScanning) {
      try {
        await scannerRef.current.stop();
      } catch {}
    }
    setStaff(null);
    setCurrentScan(null);
    setHistory([]);
    setCodeInput("");
    try {
      sessionStorage.removeItem(STORAGE_KEY);
    } catch {}
  };

  // ── Scanner actions
  const stopScanner = async () => {
    const instance = scannerRef.current;
    if (!instance?.isScanning) return;
    await instance.stop();
    await instance.clear();
    setScanning(false);
  };

  const startScanner = async () => {
    const instance = scannerRef.current;
    if (!instance || scanning) return;
    setError(null);
    try {
      await instance.start(
        { facingMode: "environment" },
        { fps: 10, qrbox: { width: 240, height: 240 } },
        async (decodedText: string) => {
          try {
            await applyScan(decodedText);
            await stopScanner();
          } catch (e) {
            setError(e instanceof Error ? e.message : "No se pudo interpretar el QR.");
          }
        },
        () => undefined,
      );
      setScanning(true);
    } catch (e) {
      setError(e instanceof Error ? e.message : "No se pudo iniciar la cámara.");
    }
  };

  const applyScan = async (rawValue: string) => {
    if (!staff) return;
    const parsed = parseCredentialQr(rawValue);

    // Submit to backend for validation + persistence
    let authorized = false;
    let reason = "UNKNOWN";
    let serverName = parsed.fullName;
    let serverType = parsed.subjectType;
    try {
      const result = await apiFetch<{
        authorized: boolean;
        reason: string;
        target: { type: string; name: string; id: string } | null;
      }>("/access-control/scan", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          code: parsed.code,
          scannedById: staff.id,
          scannedByName: staff.fullName,
          location: selectedLocation,
        }),
      });
      authorized = result.authorized;
      reason = result.reason;
      if (result.target) {
        serverName = result.target.name || serverName;
        if (result.target.type === "driver") serverType = "DRIVER";
        else if (result.target.type === "athlete") serverType = "ATHLETE";
        else if (result.target.type === "provider_participant") serverType = "STAFF";
      }
    } catch (err) {
      reason = err instanceof Error ? err.message : "Error al validar";
    }

    const record: ScanRecord = {
      ...parsed,
      fullName: serverName,
      subjectType: serverType,
      location: selectedLocation,
      scannedAt: formatScanTimestamp(new Date()),
      authorized,
      reason,
    };
    setCurrentScan(record);
    setHistory((prev) => [record, ...prev].slice(0, 10));
    setError(null);
    if (authorized) {
      setFlashOk(true);
      setTimeout(() => setFlashOk(false), 1800);
    } else {
      setFlashDenied(true);
      setTimeout(() => setFlashDenied(false), 1800);
    }
  };

  const loc = SCAN_LOCATIONS.find((l) => l.value === selectedLocation) ?? SCAN_LOCATIONS[0];

  // ── Auth screen (matches visual language of other portals, e.g. /portal/conductor)
  if (!staff) {
    return (
      <div className="flex flex-col lg:flex-row" style={{ minHeight: "100vh", background: "#020c18", position: "relative", overflow: "hidden" }}>
        <style>{`
          @keyframes pc-f1{0%,100%{transform:translateY(0px) scale(1)}50%{transform:translateY(-30px) translateX(10px) scale(1.05)}}
          @keyframes pc-f2{0%,100%{transform:translateY(0px)}50%{transform:translateY(-20px) translateX(15px)}}
          @keyframes pc-pulse{0%,100%{opacity:0.15;transform:scale(1)}50%{opacity:0.4;transform:scale(1.08)}}
          @keyframes pc-shimmer{0%{background-position:-200% center}100%{background-position:200% center}}
          @keyframes pc-in{from{opacity:0;transform:translateY(24px)}to{opacity:1;transform:translateY(0)}}
          .pc-form{animation:pc-in 0.6s cubic-bezier(0.16,1,0.3,1) both;animation-delay:0.15s;opacity:0;}
        `}</style>

        {/* Left branding panel */}
        <div className="flex flex-col justify-between p-8 lg:p-14 lg:w-[46%] lg:flex-shrink-0"
          style={{ background: "linear-gradient(160deg,#020c18 0%,#041a2e 40%,#062240 70%,#030f1e 100%)", position: "relative", overflow: "hidden", minHeight: "180px" }}>
          <div style={{ position: "absolute", inset: 0, pointerEvents: "none", backgroundImage: `linear-gradient(rgba(33,208,179,0.03) 1px,transparent 1px),linear-gradient(90deg,rgba(33,208,179,0.03) 1px,transparent 1px)`, backgroundSize: "60px 60px" }} />
          <div style={{ position: "absolute", top: "-60px", left: "-60px", width: "400px", height: "400px", borderRadius: "50%", background: "radial-gradient(ellipse,rgba(6,34,64,0.6) 0%,transparent 70%)", animation: "pc-f1 12s ease-in-out infinite", pointerEvents: "none" }} />
          <div style={{ position: "absolute", bottom: "60px", right: "-40px", width: "320px", height: "320px", borderRadius: "50%", background: "radial-gradient(ellipse,rgba(33,208,179,0.1) 0%,transparent 70%)", animation: "pc-f2 16s ease-in-out infinite", pointerEvents: "none" }} />
          {[480, 340, 200].map((size, i) => (
            <div key={i} style={{ position: "absolute", top: "50%", left: "50%", marginTop: -size / 2, marginLeft: -size / 2, width: size, height: size, borderRadius: "50%", border: `1px solid rgba(33,208,179,${0.04 + i * 0.04})`, animation: `pc-pulse 6s ease-in-out infinite ${i * 2}s`, pointerEvents: "none" }} />
          ))}
          <div style={{ position: "relative", zIndex: 1 }}>
            <img src="/branding/LOGO-SEVEN-1.png" alt="Seven Arena" className="h-14 sm:h-20 lg:h-28" style={{ width: "auto", objectFit: "contain", filter: "drop-shadow(0 0 30px rgba(33,208,179,0.4)) drop-shadow(0 4px 12px rgba(0,0,0,0.9))" }} />
          </div>
          <div style={{ position: "relative", zIndex: 1, flex: 1, display: "flex", flexDirection: "column", justifyContent: "center", gap: "16px", padding: "24px 0" }}>
            <div style={{ display: "inline-flex", alignItems: "center", gap: "8px", width: "fit-content" }}>
              <span style={{ width: 7, height: 7, borderRadius: "50%", background: "#21D0B3", boxShadow: "0 0 10px #21D0B3", display: "inline-block", animation: "pc-pulse 2s ease-in-out infinite" }} />
              <span style={{ fontSize: "10px", fontWeight: 700, letterSpacing: "0.22em", textTransform: "uppercase", color: "#21D0B3" }}>Portal de Control de Acceso</span>
            </div>
            <h1 style={{ fontSize: "clamp(28px,3vw,44px)", fontWeight: 800, lineHeight: 1.1, color: "#f8fafc", letterSpacing: "-0.02em", margin: 0 }}>
              Valida<br />
              <span style={{ background: "linear-gradient(90deg,#21D0B3 0%,#34F3C6 40%,#21D0B3 80%)", backgroundSize: "200% auto", WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent", backgroundClip: "text", animation: "pc-shimmer 4s linear infinite" }}>credenciales QR</span>
            </h1>
            <p className="hidden sm:block" style={{ fontSize: "14px", color: "rgba(255,255,255,0.45)", maxWidth: "340px", lineHeight: 1.7, margin: 0 }}>
              Escanea los códigos de los participantes en cada punto de control y registra el acceso en tiempo real.
            </p>
            <div className="hidden lg:flex flex-col" style={{ gap: "10px", marginTop: "8px" }}>
              {([
                [<svg key="qr" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="rgba(33,208,179,0.8)" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="3" width="7" height="7" rx="1" /><rect x="14" y="3" width="7" height="7" rx="1" /><rect x="3" y="14" width="7" height="7" rx="1" /><path d="M14 14h3M20 14v3M14 17v4M17 20h4" /></svg>, "Escaneo QR con cámara"],
                [<svg key="ok" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="rgba(33,208,179,0.8)" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="M22 11.08V12a10 10 0 1 1-5.93-9.14" /><polyline points="22 4 12 14.01 9 11.01" /></svg>, "Validación en tiempo real"],
                [<svg key="log" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="rgba(33,208,179,0.8)" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" /><polyline points="14 2 14 8 20 8" /><line x1="16" y1="13" x2="8" y2="13" /><line x1="16" y1="17" x2="8" y2="17" /></svg>, "Trazabilidad completa"],
              ] as [React.ReactNode, string][]).map(([icon, label]) => (
                <div key={label} style={{ display: "flex", alignItems: "center", gap: "10px" }}>
                  <span style={{ display: "flex", alignItems: "center", flexShrink: 0 }}>{icon}</span>
                  <span style={{ fontSize: "13px", color: "rgba(255,255,255,0.6)", fontWeight: 500 }}>{label}</span>
                </div>
              ))}
            </div>
          </div>
          <div className="hidden lg:flex" style={{ position: "relative", zIndex: 1, borderTop: "1px solid rgba(255,255,255,0.07)", paddingTop: "20px" }}>
            {[["Acceso seguro", "SSL / HTTPS"], ["Registro en vivo", "Tiempo real"], ["Multi-evento", "Global"]].map(([title, sub], i, arr) => (
              <div key={title} style={{ flex: 1, paddingRight: i < arr.length - 1 ? "20px" : "0", borderRight: i < arr.length - 1 ? "1px solid rgba(255,255,255,0.06)" : "none", paddingLeft: i > 0 ? "20px" : "0" }}>
                <p style={{ fontSize: "14px", fontWeight: 800, color: "#21D0B3", margin: 0, lineHeight: 1 }}>{title}</p>
                <p style={{ fontSize: "10px", color: "rgba(255,255,255,0.32)", margin: "3px 0 0", letterSpacing: "0.05em", textTransform: "uppercase" }}>{sub}</p>
              </div>
            ))}
          </div>
        </div>

        {/* Right form panel */}
        <div className="flex-1 flex items-center justify-center p-5 sm:p-8 lg:p-16"
          style={{ background: "linear-gradient(160deg,#030f1e 0%,#041a2e 50%,#020c18 100%)", position: "relative", overflow: "hidden" }}>
          <div style={{ position: "absolute", top: "30%", left: "50%", transform: "translate(-50%,-50%)", width: "500px", height: "500px", borderRadius: "50%", background: "radial-gradient(ellipse,rgba(6,34,64,0.4) 0%,transparent 70%)", pointerEvents: "none" }} />
          <div style={{ position: "absolute", bottom: "-50px", right: "-50px", width: "280px", height: "280px", borderRadius: "50%", background: "radial-gradient(ellipse,rgba(33,208,179,0.08) 0%,transparent 70%)", pointerEvents: "none" }} />
          <div className="pc-form relative z-10 w-full" style={{ maxWidth: "420px" }}>
            <h2 style={{ fontSize: "24px", fontWeight: 700, color: "rgba(255,255,255,0.95)", marginBottom: "6px" }}>Acceder al portal</h2>
            <p style={{ fontSize: "13px", color: "rgba(255,255,255,0.4)", marginBottom: "28px", lineHeight: 1.6 }}>
              Ingresa tu código de staff para iniciar el control de acceso.
            </p>
            <div style={{ display: "grid", gap: "12px" }}>
              <div>
                <span style={{ fontSize: "11px", fontWeight: 600, letterSpacing: "0.12em", textTransform: "uppercase", color: "rgba(255,255,255,0.4)", display: "block", marginBottom: "8px" }}>Código de staff</span>
                <input
                  value={codeInput}
                  onChange={(e) => setCodeInput(e.target.value)}
                  onKeyDown={(e) => e.key === "Enter" && attemptAuth()}
                  placeholder="Ingresa tu código"
                  autoFocus
                  style={{ width: "100%", padding: "16px", borderRadius: "14px", border: "1px solid rgba(33,208,179,0.2)", background: "rgba(255,255,255,0.05)", color: "rgba(255,255,255,0.9)", fontSize: "15px", outline: "none", fontWeight: 500, boxSizing: "border-box" }}
                />
              </div>
              <button
                type="button"
                onClick={attemptAuth}
                disabled={authLoading || !codeInput.trim()}
                style={{ width: "100%", padding: "17px", borderRadius: "14px", border: "none", background: "linear-gradient(135deg,#34F3C6 0%,#21D0B3 50%,#15B09A 100%)", color: "#0d1b3e", fontSize: "16px", fontWeight: 700, cursor: authLoading ? "not-allowed" : "pointer", opacity: authLoading ? 0.7 : 1, letterSpacing: "0.03em", boxShadow: "0 4px 20px rgba(33,208,179,0.35)" }}
              >
                {authLoading ? "Validando..." : "Ingresar al scanner"}
              </button>
              {authError && <p style={{ color: "#fca5a5", fontSize: "13px", textAlign: "center" }}>{authError}</p>}
            </div>

            <div style={{ display: "flex", alignItems: "center", gap: "12px", margin: "24px 0" }}>
              <div style={{ flex: 1, height: 1, background: "rgba(255,255,255,0.08)" }} />
              <span style={{ fontSize: "11px", color: "rgba(255,255,255,0.25)", letterSpacing: "0.06em", whiteSpace: "nowrap" }}>¿NO TIENES CÓDIGO?</span>
              <div style={{ flex: 1, height: 1, background: "rgba(255,255,255,0.08)" }} />
            </div>

            <div style={{ display: "grid", gap: "12px" }}>
              <div>
                <span style={{ fontSize: "11px", fontWeight: 600, letterSpacing: "0.12em", textTransform: "uppercase", color: "rgba(255,255,255,0.4)", display: "block", marginBottom: "8px" }}>Correo electrónico</span>
                <input
                  type="email"
                  value={requestEmail}
                  onChange={(e) => setRequestEmail(e.target.value)}
                  onKeyDown={(e) => e.key === "Enter" && requestAccess()}
                  placeholder="email@dominio.com"
                  style={{ width: "100%", padding: "16px", borderRadius: "14px", border: "1px solid rgba(255,255,255,0.1)", background: "rgba(255,255,255,0.05)", color: "rgba(255,255,255,0.9)", fontSize: "15px", outline: "none", fontWeight: 500, boxSizing: "border-box" }}
                />
              </div>
              <button
                type="button"
                onClick={requestAccess}
                disabled={requestLoading || !requestEmail.trim()}
                style={{ width: "100%", padding: "16px", borderRadius: "14px", border: "1px solid rgba(33,208,179,0.25)", background: "rgba(33,208,179,0.06)", color: "rgba(255,255,255,0.8)", fontSize: "15px", fontWeight: 500, cursor: requestLoading ? "not-allowed" : "pointer", opacity: requestLoading ? 0.7 : 1 }}
              >
                {requestLoading ? "Enviando..." : "Solicitar código"}
              </button>
              {requestStatus && <p style={{ color: "#6ee7b7", fontSize: "13px" }}>{requestStatus}</p>}
              {requestError && <p style={{ color: "#fca5a5", fontSize: "13px" }}>{requestError}</p>}
            </div>

            <p style={{ fontSize: "11px", color: "rgba(255,255,255,0.35)", marginTop: "24px", textAlign: "center", lineHeight: 1.6 }}>
              Solo personal registrado como proveedor tipo Staff puede acceder.
            </p>
          </div>
        </div>
      </div>
    );
  }

  // ── Scanner screen (replicates ScannerPortal UX)
  return (
    <main style={{ minHeight: "100vh", background: "#f0f3fa", color: "#0f172a", fontFamily: "inherit" }}>
      <style>{`
        @keyframes scanLine {
          0%   { top: 0%; opacity: 1; }
          48%  { opacity: 1; }
          50%  { top: 100%; opacity: 0; }
          100% { top: 100%; opacity: 0; }
        }
        @keyframes successFlash {
          0%   { opacity: 0; transform: scale(0.85); }
          30%  { opacity: 1; transform: scale(1.04); }
          100% { opacity: 0; transform: scale(1.08); }
        }
        @keyframes scannerPulse {
          0%, 100% { opacity: 1; }
          50%      { opacity: 0.5; }
        }
      `}</style>

      <div style={{ maxWidth: "1400px", margin: "0 auto", padding: "20px", display: "flex", flexDirection: "column", minHeight: "100vh", gap: "16px" }}>

        {/* ── Header banner */}
        <section style={{
          borderRadius: "24px",
          background: "#ffffff",
          border: "1px solid #e2e8f0",
          padding: "24px 28px",
          boxShadow: "0 1px 4px rgba(15,23,42,0.06)",
        }}>
          <div style={{ display: "flex", flexWrap: "wrap", alignItems: "center", justifyContent: "space-between", gap: "20px" }}>
            <div>
              <span style={{ display: "inline-flex", alignItems: "center", gap: "6px", background: "rgba(33,208,179,0.08)", border: "1px solid rgba(33,208,179,0.25)", borderRadius: "99px", padding: "3px 12px", fontSize: "10px", fontWeight: 700, letterSpacing: "0.25em", textTransform: "uppercase", color: "#21D0B3" }}>
                <span style={{ width: "6px", height: "6px", borderRadius: "50%", background: "#21D0B3", display: "inline-block" }} />
                Control de acceso
              </span>
              <h1 style={{ marginTop: "10px", fontSize: "clamp(1.4rem, 2.5vw, 2rem)", fontWeight: 800, lineHeight: 1.1, color: "#0f172a" }}>
                Escaneo QR de credenciales
              </h1>
              <p style={{ marginTop: "6px", fontSize: "14px", color: "#64748b", maxWidth: "480px" }}>
                {staff.fullName} · {staff.providerName || "Staff"}
              </p>
            </div>

            <div style={{ display: "flex", alignItems: "flex-start", gap: "12px", flexWrap: "wrap" }}>
              {/* Location pills */}
              <div style={{ display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: "8px", minWidth: "340px" }}>
                {SCAN_LOCATIONS.map((item) => {
                  const active = item.value === selectedLocation;
                  return (
                    <button
                      key={item.value}
                      type="button"
                      onClick={() => setSelectedLocation(item.value)}
                      style={{
                        borderRadius: "14px",
                        border: active ? `2px solid ${item.color}` : "1px solid #e2e8f0",
                        background: active ? item.bg : "#f8fafc",
                        padding: "10px 8px",
                        cursor: "pointer",
                        transition: "all 200ms",
                        textAlign: "left",
                        boxShadow: active ? `0 2px 12px ${item.border}` : "none",
                      }}
                    >
                      <div style={{ color: active ? item.color : "#94a3b8", marginBottom: "4px" }}>
                        {LOCATION_ICONS[item.value]}
                      </div>
                      <div style={{ fontSize: "9px", fontWeight: 700, letterSpacing: "0.2em", textTransform: "uppercase", color: active ? item.color : "#94a3b8" }}>Lugar</div>
                      <div style={{ fontSize: "13px", fontWeight: 700, color: active ? "#0f172a" : "#64748b", marginTop: "2px" }}>{item.label}</div>
                    </button>
                  );
                })}
              </div>
              <button
                type="button"
                onClick={logout}
                style={{
                  background: "#ffffff",
                  border: "1px solid #e2e8f0",
                  borderRadius: "10px",
                  padding: "8px 14px",
                  fontSize: "12px",
                  fontWeight: 600,
                  color: "#64748b",
                  cursor: "pointer",
                  alignSelf: "flex-start",
                }}
              >
                Cerrar sesión
              </button>
            </div>
          </div>
        </section>

        {/* ── Main grid */}
        <div style={{ display: "grid", gridTemplateColumns: "1.1fr 0.9fr", gap: "16px", flex: 1, alignItems: "start" }}>

          {/* Camera panel */}
          <div style={{ borderRadius: "24px", border: "1px solid #e2e8f0", background: "#ffffff", boxShadow: "0 1px 4px rgba(15,23,42,0.06)", overflow: "hidden" }}>
            <div style={{ borderBottom: "1px solid #e2e8f0", background: "#f8fafc", padding: "16px 20px", display: "flex", alignItems: "center", justifyContent: "space-between", flexWrap: "wrap", gap: "12px" }}>
              <div>
                <p style={{ fontSize: "10px", fontWeight: 700, letterSpacing: "0.22em", textTransform: "uppercase", color: "#94a3b8" }}>Cámara activa</p>
                <p style={{ marginTop: "3px", fontSize: "16px", fontWeight: 700, color: "#0f172a", display: "flex", alignItems: "center", gap: "8px" }}>
                  <span style={{ color: loc.color }}>{LOCATION_ICONS[selectedLocation]}</span>
                  Escaneo en {loc.label}
                </p>
              </div>
              <div style={{ display: "flex", gap: "8px" }}>
                <button
                  type="button"
                  disabled={!scannerReady || scanning}
                  onClick={() => void startScanner()}
                  style={{
                    background: scanning ? loc.bg : `linear-gradient(135deg, #21D0B3, #14AE98)`,
                    border: scanning ? `1px solid ${loc.border}` : "none",
                    borderRadius: "10px", padding: "8px 18px",
                    fontSize: "13px", fontWeight: 700,
                    color: scanning ? loc.color : "#ffffff",
                    cursor: scanning || !scannerReady ? "not-allowed" : "pointer",
                    boxShadow: scanning ? "none" : "0 2px 10px rgba(33,208,179,0.35)",
                    display: "flex", alignItems: "center", gap: "6px",
                  }}
                >
                  {scanning ? (
                    <>
                      <span style={{ width: "8px", height: "8px", borderRadius: "50%", background: loc.color, animation: "scannerPulse 1s infinite", display: "inline-block" }} />
                      Escaneando...
                    </>
                  ) : (
                    <>
                      <svg width="13" height="13" viewBox="0 0 24 24" fill="currentColor"><polygon points="5 3 19 12 5 21 5 3" /></svg>
                      Iniciar cámara
                    </>
                  )}
                </button>
                <button
                  type="button"
                  disabled={!scanning}
                  onClick={() => void stopScanner()}
                  style={{ background: "#ffffff", border: "1px solid #e2e8f0", borderRadius: "10px", padding: "8px 16px", fontSize: "13px", fontWeight: 600, color: scanning ? "#475569" : "#cbd5e1", cursor: scanning ? "pointer" : "not-allowed" }}
                >
                  <svg width="10" height="10" viewBox="0 0 24 24" fill="currentColor" style={{ marginRight: "6px" }}><rect x="3" y="3" width="18" height="18" /></svg>
                  Detener
                </button>
              </div>
            </div>

            {/* Camera viewport */}
            <div style={{ padding: "16px" }}>
              <div style={{
                borderRadius: "20px",
                border: `2px solid ${scanning ? loc.color : "#e2e8f0"}`,
                background: "linear-gradient(180deg, #020817 0%, #0a1020 100%)",
                padding: "12px",
                position: "relative",
                overflow: "hidden",
                transition: "border-color 0.3s",
              }}>
                {(["top-left", "top-right", "bottom-left", "bottom-right"] as const).map((pos) => (
                  <div key={pos} style={{
                    position: "absolute", width: "20px", height: "20px",
                    ...(pos.includes("top") ? { top: "12px" } : { bottom: "12px" }),
                    ...(pos.includes("left") ? { left: "12px" } : { right: "12px" }),
                    borderTop: pos.includes("top") ? `2px solid ${loc.color}` : "none",
                    borderBottom: pos.includes("bottom") ? `2px solid ${loc.color}` : "none",
                    borderLeft: pos.includes("left") ? `2px solid ${loc.color}` : "none",
                    borderRight: pos.includes("right") ? `2px solid ${loc.color}` : "none",
                    opacity: scanning ? 1 : 0.35,
                    transition: "opacity 0.3s",
                  }} />
                ))}

                {scanning && (
                  <div style={{
                    position: "absolute", left: "12px", right: "12px", height: "2px",
                    background: `linear-gradient(90deg, transparent, ${loc.color}, transparent)`,
                    boxShadow: `0 0 8px ${loc.color}`,
                    animation: "scanLine 2s linear infinite",
                    zIndex: 10,
                  }} />
                )}

                <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: "10px", padding: "0 4px" }}>
                  <span style={{ fontSize: "10px", fontWeight: 700, letterSpacing: "0.2em", textTransform: "uppercase", color: "rgba(255,255,255,0.3)" }}>Cámara posterior</span>
                  <span style={{ fontSize: "10px", fontWeight: 700, letterSpacing: "0.15em", textTransform: "uppercase", color: scanning ? "#10b981" : "rgba(255,255,255,0.3)", display: "flex", alignItems: "center", gap: "5px" }}>
                    {scanning && <span style={{ width: "6px", height: "6px", borderRadius: "50%", background: "#10b981", animation: "scannerPulse 1s infinite", display: "inline-block" }} />}
                    {scanning ? "Activa" : "En espera"}
                  </span>
                </div>

                <div id={regionId} style={{ minHeight: "340px", width: "100%", overflow: "hidden", borderRadius: "14px", background: "#050c18" }} />
              </div>

              {error && (
                <div style={{ marginTop: "12px", borderRadius: "12px", border: "1px solid rgba(239,68,68,0.25)", background: "rgba(239,68,68,0.06)", padding: "10px 14px", fontSize: "13px", color: "#ef4444", display: "flex", alignItems: "center", gap: "8px" }}>
                  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><circle cx="12" cy="12" r="10" /><line x1="12" y1="8" x2="12" y2="12" /><line x1="12" y1="16" x2="12.01" y2="16" /></svg>
                  {error}
                </div>
              )}
            </div>
          </div>

          {/* Right panels */}
          <div style={{ display: "flex", flexDirection: "column", gap: "14px" }}>

            {/* Success flash */}
            {flashOk && (
              <div style={{ position: "fixed", inset: 0, zIndex: 50, display: "flex", alignItems: "center", justifyContent: "center", pointerEvents: "none" }}>
                <div style={{ background: "rgba(33,208,179,0.12)", border: "2px solid #21D0B3", borderRadius: "50%", width: "160px", height: "160px", display: "flex", alignItems: "center", justifyContent: "center", animation: "successFlash 1.8s ease forwards", boxShadow: "0 0 60px rgba(33,208,179,0.4)" }}>
                  <svg width="64" height="64" viewBox="0 0 24 24" fill="none" stroke="#21D0B3" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                    <path d="M20 6L9 17l-5-5" />
                  </svg>
                </div>
              </div>
            )}

            {/* Denied flash */}
            {flashDenied && (
              <div style={{ position: "fixed", inset: 0, zIndex: 50, display: "flex", alignItems: "center", justifyContent: "center", pointerEvents: "none" }}>
                <div style={{ background: "rgba(239,68,68,0.12)", border: "2px solid #ef4444", borderRadius: "50%", width: "160px", height: "160px", display: "flex", alignItems: "center", justifyContent: "center", animation: "successFlash 1.8s ease forwards", boxShadow: "0 0 60px rgba(239,68,68,0.4)" }}>
                  <svg width="64" height="64" viewBox="0 0 24 24" fill="none" stroke="#ef4444" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                    <line x1="18" y1="6" x2="6" y2="18" /><line x1="6" y1="6" x2="18" y2="18" />
                  </svg>
                </div>
              </div>
            )}

            {/* Result panel */}
            <div style={{
              borderRadius: "20px",
              border: `1px solid ${currentScan ? (currentScan.authorized ? loc.color + "40" : "rgba(239,68,68,0.4)") : "#e2e8f0"}`,
              background: "#ffffff",
              overflow: "hidden",
              boxShadow: currentScan ? (currentScan.authorized ? `0 4px 20px ${loc.border}` : "0 4px 20px rgba(239,68,68,0.15)") : "0 1px 4px rgba(15,23,42,0.06)",
              transition: "box-shadow 0.4s, border-color 0.4s",
            }}>
              <div style={{
                borderBottom: `1px solid ${currentScan ? (currentScan.authorized ? loc.color + "25" : "rgba(239,68,68,0.3)") : "#e2e8f0"}`,
                background: currentScan ? (currentScan.authorized ? loc.bg : "rgba(239,68,68,0.06)") : "#f8fafc",
                padding: "14px 18px",
              }}>
                <p style={{ fontSize: "10px", fontWeight: 700, letterSpacing: "0.22em", textTransform: "uppercase", color: currentScan ? (currentScan.authorized ? loc.color : "#ef4444") : "#94a3b8" }}>
                  {currentScan ? (currentScan.authorized ? "Acceso autorizado" : "Acceso denegado") : "Último escaneo"}
                </p>
                <p style={{ marginTop: "3px", fontSize: "16px", fontWeight: 700, color: "#0f172a" }}>Resultado de validación</p>
              </div>
              <div style={{ padding: "16px" }}>
                {currentScan ? (
                  <div style={{ display: "flex", flexDirection: "column", gap: "10px" }}>
                    {/* Location banner with OK/denied badge */}
                    <div style={{
                      borderRadius: "14px",
                      background: currentScan.authorized ? loc.bg : "rgba(239,68,68,0.06)",
                      border: `1px solid ${currentScan.authorized ? loc.border : "rgba(239,68,68,0.3)"}`,
                      padding: "14px 16px",
                    }}>
                      <div style={{ display: "flex", alignItems: "center", gap: "10px" }}>
                        <div style={{
                          width: "40px", height: "40px", borderRadius: "12px",
                          background: "#ffffff",
                          border: `1px solid ${currentScan.authorized ? loc.border : "rgba(239,68,68,0.3)"}`,
                          display: "flex", alignItems: "center", justifyContent: "center",
                          color: currentScan.authorized ? loc.color : "#ef4444",
                          flexShrink: 0,
                        }}>
                          {LOCATION_ICONS[currentScan.location]}
                        </div>
                        <div style={{ flex: 1 }}>
                          <p style={{ fontSize: "10px", fontWeight: 700, letterSpacing: "0.2em", textTransform: "uppercase", color: "#94a3b8" }}>
                            {currentScan.authorized ? "Acceso validado" : currentScan.reason}
                          </p>
                          <p style={{ fontSize: "18px", fontWeight: 800, color: "#0f172a" }}>{SCAN_LOCATIONS.find((l) => l.value === currentScan.location)?.label}</p>
                          <p style={{ fontSize: "11px", color: "#64748b", marginTop: "2px" }}>{currentScan.scannedAt}</p>
                        </div>
                        <div style={{
                          width: "36px", height: "36px", borderRadius: "50%",
                          background: currentScan.authorized ? "rgba(33,208,179,0.1)" : "rgba(239,68,68,0.1)",
                          border: `1px solid ${currentScan.authorized ? "rgba(33,208,179,0.3)" : "rgba(239,68,68,0.3)"}`,
                          display: "flex", alignItems: "center", justifyContent: "center",
                          flexShrink: 0,
                        }}>
                          {currentScan.authorized ? (
                            <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="#21D0B3" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                              <path d="M20 6L9 17l-5-5" />
                            </svg>
                          ) : (
                            <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="#ef4444" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                              <line x1="18" y1="6" x2="6" y2="18" /><line x1="6" y1="6" x2="18" y2="18" />
                            </svg>
                          )}
                        </div>
                      </div>
                    </div>

                    {/* Name */}
                    <div style={{ borderRadius: "12px", border: "1px solid #e2e8f0", background: "#f8fafc", padding: "12px 14px" }}>
                      <p style={{ fontSize: "10px", fontWeight: 700, letterSpacing: "0.2em", textTransform: "uppercase", color: "#94a3b8" }}>Nombre</p>
                      <p style={{ marginTop: "4px", fontSize: "18px", fontWeight: 800, color: "#0f172a" }}>{currentScan.fullName}</p>
                    </div>

                    {/* 2-col grid */}
                    <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "8px" }}>
                      {[
                        { label: "Delegación", value: currentScan.delegation },
                        { label: "Disciplina", value: currentScan.discipline },
                        {
                          label: "Tipo",
                          value:
                            currentScan.subjectType === "DRIVER"
                              ? "Conductor"
                              : currentScan.subjectType === "STAFF"
                                ? "Staff"
                                : "Participante",
                        },
                        { label: "Evento", value: currentScan.eventName },
                      ].map((item) => (
                        <div key={item.label} style={{ borderRadius: "12px", border: "1px solid #e2e8f0", background: "#f8fafc", padding: "10px 12px" }}>
                          <p style={{ fontSize: "9px", fontWeight: 700, letterSpacing: "0.18em", textTransform: "uppercase", color: "#94a3b8" }}>{item.label}</p>
                          <p style={{ marginTop: "4px", fontSize: "13px", fontWeight: 700, color: "#0f172a" }}>{item.value}</p>
                        </div>
                      ))}
                    </div>
                  </div>
                ) : (
                  <div style={{ borderRadius: "14px", border: "1px dashed #e2e8f0", background: "#f8fafc", padding: "40px 20px", textAlign: "center" }}>
                    <div style={{ display: "flex", justifyContent: "center", marginBottom: "12px", opacity: 0.3 }}>
                      <svg width="36" height="36" viewBox="0 0 24 24" fill="none" stroke="#94a3b8" strokeWidth="1.5" strokeLinecap="round">
                        <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z" />
                        <circle cx="12" cy="13" r="4" />
                      </svg>
                    </div>
                    <p style={{ fontSize: "14px", color: "#94a3b8", lineHeight: 1.6 }}>Aún no hay lecturas.<br />Selecciona el lugar y escanea una credencial.</p>
                  </div>
                )}
              </div>
            </div>

            {/* History */}
            <div style={{ borderRadius: "20px", border: "1px solid #e2e8f0", background: "#ffffff", overflow: "hidden", boxShadow: "0 1px 4px rgba(15,23,42,0.06)" }}>
              <div style={{ borderBottom: "1px solid #e2e8f0", background: "#f8fafc", padding: "14px 18px", display: "flex", alignItems: "center", justifyContent: "space-between" }}>
                <div>
                  <p style={{ fontSize: "10px", fontWeight: 700, letterSpacing: "0.22em", textTransform: "uppercase", color: "#94a3b8" }}>Historial</p>
                  <p style={{ marginTop: "3px", fontSize: "16px", fontWeight: 700, color: "#0f172a" }}>Últimas validaciones</p>
                </div>
                {history.length > 0 && (
                  <span style={{ background: "rgba(33,208,179,0.08)", border: "1px solid rgba(33,208,179,0.25)", borderRadius: "99px", padding: "3px 10px", fontSize: "12px", fontWeight: 700, color: "#21D0B3" }}>
                    {history.length}
                  </span>
                )}
              </div>
              <div style={{ padding: "12px", display: "flex", flexDirection: "column", gap: "8px" }}>
                {history.length === 0 ? (
                  <div style={{ borderRadius: "12px", border: "1px dashed #e2e8f0", background: "#f8fafc", padding: "28px 16px", textAlign: "center", fontSize: "13px", color: "#94a3b8" }}>
                    Sin escaneos registrados en esta sesión.
                  </div>
                ) : (
                  history.map((item, index) => {
                    const itemLoc = SCAN_LOCATIONS.find((l) => l.value === item.location) ?? SCAN_LOCATIONS[0];
                    const okColor = item.authorized ? itemLoc.color : "#ef4444";
                    const okBg = item.authorized ? itemLoc.bg : "rgba(239,68,68,0.08)";
                    const okBorder = item.authorized ? itemLoc.border : "rgba(239,68,68,0.3)";
                    return (
                      <div key={`${item.rawValue}-${index}`} style={{
                        borderRadius: "14px",
                        border: `1px solid ${okBorder}`,
                        borderLeft: `3px solid ${okColor}`,
                        background: index === 0 ? okBg : "#f8fafc",
                        padding: "10px 14px",
                        display: "flex", alignItems: "center", gap: "12px",
                      }}>
                        <div style={{ color: okColor, flexShrink: 0 }}>{LOCATION_ICONS[item.location]}</div>
                        <div style={{ flex: 1, minWidth: 0 }}>
                          <p style={{ fontWeight: 700, fontSize: "13px", color: "#0f172a", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>{item.fullName}</p>
                          <p style={{ marginTop: "2px", fontSize: "11px", color: "#64748b" }}>{item.delegation} · {item.discipline}</p>
                          <p style={{ marginTop: "1px", fontSize: "10px", color: "#94a3b8", fontVariantNumeric: "tabular-nums" }}>{item.scannedAt}</p>
                        </div>
                        <span style={{
                          background: okBg,
                          border: `1px solid ${okBorder}`,
                          borderRadius: "99px", padding: "3px 10px",
                          fontSize: "10px", fontWeight: 700,
                          color: okColor, flexShrink: 0,
                        }}>
                          {item.authorized ? itemLoc.label : "Denegado"}
                        </span>
                      </div>
                    );
                  })
                )}
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
  );
}
