import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';
import * as fs from 'fs';
import * as path from 'path';

async function bootstrap() {
  // Use HTTPS if certificates exist (generated by Next.js --experimental-https)
  const certDir = path.resolve(process.cwd(), 'frontend', 'certificates');
  const keyPath = path.join(certDir, 'localhost-key.pem');
  const certPath = path.join(certDir, 'localhost.pem');
  // Skip HTTPS if explicitly disabled (useful for LAN/mobile testing)
  const disableHttps = process.env.NO_HTTPS === '1' || process.env.NO_HTTPS === 'true';
  const httpsOptions = !disableHttps && fs.existsSync(keyPath) && fs.existsSync(certPath)
    ? { key: fs.readFileSync(keyPath), cert: fs.readFileSync(certPath) }
    : undefined;

  const app = await NestFactory.create(AppModule, {
    bodyParser: false,
    ...(httpsOptions ? { httpsOptions } : {}),
  });
  app.use(require('express').json({ limit: '50mb' }));
  app.use(require('express').urlencoded({ limit: '50mb', extended: true }));
  const allowedOrigins = new Set([
    'http://localhost:3000',
    'http://localhost:3001',
    'https://localhost:3000',
    'https://localhost:3001',
    'https://proyect-seven-q9q8jgx37-ariels-projects-b6125cb2.vercel.app',
    'https://proyect-seven-cqgvzzv14-ariels-projects-b6125cb2.vercel.app',
    'https://seven.management',
    'https://www.seven.management',
    'https://sevenarena.app',
    'https://www.sevenarena.app'
  ]);
  app.enableCors({
    origin: (origin, callback) => {
      if (!origin) return callback(null, true);
      if (allowedOrigins.has(origin)) return callback(null, true);
      if (origin.endsWith('.vercel.app')) return callback(null, true);
      // Allow local network access (e.g., mobile testing via LAN IP)
      if (/^https?:\/\/(192\.168\.|10\.|172\.(1[6-9]|2\d|3[01])\.|localhost)/.test(origin)) return callback(null, true);
      return callback(new Error('Not allowed by CORS'));
    },
    methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS'],
    allowedHeaders: ['Content-Type', 'Authorization'],
    exposedHeaders: ['Authorization', 'x-refresh-token'],
    credentials: true,
  });
  const port = Number(process.env.PORT) || 3000;
  await app.listen(port, '0.0.0.0');
  console.log(`Listening on ${port} (${httpsOptions ? 'HTTPS' : 'HTTP'})`);
}
bootstrap();
